import { contentBundleSchema, SCHEMA_VERSION, type ContentBundle } from '@aukrug/content';

import snapshotJson from '../../../content/bundle.json';

/** Content shipped with the app build (generated by `npm run content:render`). */
export const snapshot: ContentBundle = contentBundleSchema.parse(snapshotJson);

export type ParsedRemote =
  | { ok: true; bundle: ContentBundle }
  | { ok: false; reason: 'update-required' | 'invalid' };

/** Validates downloaded content; newer schema versions require an app update. */
export function parseRemoteBundle(data: unknown): ParsedRemote {
  const version = (data as { schemaVersion?: unknown } | null)?.schemaVersion;
  if (typeof version === 'number' && version > SCHEMA_VERSION) return { ok: false, reason: 'update-required' };
  const result = contentBundleSchema.safeParse(data);
  return result.success ? { ok: true, bundle: result.data } : { ok: false, reason: 'invalid' };
}
